apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ecsdemo-frontend # @TODO: TEMPLATE
  labels:
    apps.tanzu.vmware.com/workload-type: source-to-gitops-service-onboarding-ci
    app.kubernetes.io/part-of: ecsdemo-frontend # @TODO: TEMPLATE
    # apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  # build:
  #   env:
  #   - name: BP_JVM_VERSION
  #     value: "17"
  env:
  # - name: GREETING_MSG
  #   value: I'm a hungry Panda!
  # - name: GREETING_DESC
  #   value: I eat bamboo all day
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  # - name: testing_pipeline_matching_labels
  #   value:
  #     apps.tanzu.vmware.com/framework: maven
  #     apps.tanzu.vmware.com/pipeline: test
  # - name: api_descriptor
  #   value:
  #     type: openapi
  #     location:
  #       path: /api-docs
  #     owner: aws-containers
  #     system: ecsdemo-frontend
  #     description: A set of API endpoints to view k8s data of hungry-panda application.
  source:
    git:
      ref:
        branch: main  # @TODO: TEMPLATE
      url: https://github.com/GuyBalmas/aws-blueprints-app-example.git  # @TODO: TEMPLATE
